/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = 2;
export type Units = "feet";
export type Id = string;
export type Name = string;
export type ElevationFt = number;
export type HeightFt = number;
export type Floors = Floor[];
export type Id1 = string;
export type FloorId = string;
export type X = number;
export type Y = number;
export type Vertices = Vertex[];
export type Id2 = string;
export type FloorId1 = string;
export type StartId = string;
export type EndId = string;
export type ThicknessFt = number;
export type HeightFt1 = number;
export type Structural = "loadbearing" | "nonstructural" | "unknown";
export type Locked = boolean;
export type Material = string;
export type Confidence = number;
export type DocumentId = string;
export type SheetId = string;
export type Page = number | null;
export type Method = string;
export type Assumed = boolean;
export type Walls = BuildingWall[];
export type Id3 = string;
export type WallId = string;
export type Kind = "door" | "window";
export type OffsetFt = number;
export type WidthFt = number;
export type HeightFt2 = number;
export type SillFt = number;
export type Hinge = "left" | "right";
export type Swing = "in" | "out";
export type ClearWidthFt = number | null;
export type Openings = Opening[];
export type Id4 = string;
export type FloorId2 = string;
export type Name1 = string;
export type Category = string;
export type TypeRef = string;
export type Polygon = [number, number][];
export type WallIds = string[];
export type FloorMaterial = string;
export type Confidence1 = number;
export type NeedsReview = boolean;
export type InstanceCount = number;
export type Rooms = Room[];
export type Id5 = string;
export type FloorId3 = string;
export type AssetId = string;
export type Kind1 = string;
export type X1 = number;
export type Y1 = number;
export type RotationDeg = number;
export type WidthFt1 = number;
export type DepthFt = number;
export type HeightFt3 = number;
export type Objects = PlacedObject[];
export type TypeRef1 = string;
export type Name2 = string;
export type Label = string;
export type Category1 = string;
export type Polygon1 = [number, number][];
export type AreaSqft = number;
export type AspectRatio = number;
export type Kind2 = string;
export type X2 = number;
export type Y2 = number;
export type AssetId1 = string;
export type Fixtures = CatalogueFixture[];
export type InstanceCount1 = number;
export type TypeCatalogue = TypeCatalogueEntry[];
export type SunAzimuth = number;
export type Time = number;
export type Season = "spring" | "summer" | "autumn" | "winter";
export type Lat = number | null;
export type Lon = number | null;
export type RotationDeg1 = number;
export type GroundOffsetFt = number;
export type Address = string;
export type Id6 = string;
export type Kind3 = string;
export type Message = string;
export type DocumentId1 = string;
export type SheetId1 = string;
export type EntityIds = string[];
export type Status = "pending" | "resolved";
export type Review = ReviewItem[];
export type ProjectId = string;
export type Name3 = string;
export type Revision = number;
export type CreatedAt = string;
export type UpdatedAt = string;
export type Name4 = string;
export type BuildingUse = string;
export type Floors1 = string;
export type Rooms1 = string;
export type Area = string;
export type Style = string;
export type Prompt = string;
export type Rules = {
  [k: string]: unknown;
}[];
export type Checks = {
  [k: string]: unknown;
}[];
export type Files = {
  [k: string]: unknown;
}[];
export type Sheets = {
  [k: string]: unknown;
}[];
export type CanUndo = boolean;
export type CanRedo = boolean;
export type Kind4 = string;
export type TargetId = string;

export interface Contracts {
  building: Building;
  project: DesktopProject;
  command: ModelCommand;
  [k: string]: unknown;
}
export interface Building {
  schema_version: SchemaVersion;
  units: Units;
  floors: Floors;
  vertices: Vertices;
  walls: Walls;
  openings: Openings;
  rooms: Rooms;
  objects: Objects;
  type_catalogue: TypeCatalogue;
  environment: Environment;
  site: Site;
  review: Review;
  [k: string]: unknown;
}
export interface Floor {
  id: Id;
  name: Name;
  elevation_ft: ElevationFt;
  height_ft: HeightFt;
}
export interface Vertex {
  id: Id1;
  floor_id: FloorId;
  x: X;
  y: Y;
}
export interface BuildingWall {
  id: Id2;
  floor_id: FloorId1;
  start_id: StartId;
  end_id: EndId;
  thickness_ft: ThicknessFt;
  height_ft: HeightFt1;
  structural: Structural;
  locked: Locked;
  material: Material;
  confidence: Confidence;
  source: Source;
}
export interface Source {
  document_id: DocumentId;
  sheet_id: SheetId;
  page: Page;
  method: Method;
  assumed: Assumed;
  [k: string]: unknown;
}
export interface Opening {
  id: Id3;
  wall_id: WallId;
  kind: Kind;
  offset_ft: OffsetFt;
  width_ft: WidthFt;
  height_ft: HeightFt2;
  sill_ft: SillFt;
  hinge: Hinge;
  swing: Swing;
  clear_width_ft: ClearWidthFt;
  reliability?: 'ok' | 'suspect';
  reliability_reason?: string;
  source: Source;
}
export interface Room {
  id: Id4;
  floor_id: FloorId2;
  name: Name1;
  category: Category;
  type_ref: TypeRef;
  polygon: Polygon;
  wall_ids: WallIds;
  floor_material: FloorMaterial;
  confidence: Confidence1;
  needs_review: NeedsReview;
  instance_count?: InstanceCount;
  reliability?: 'ok' | 'suspect';
  reliability_reason?: string;
  source: Source;
}
export interface PlacedObject {
  id: Id5;
  floor_id: FloorId3;
  asset_id: AssetId;
  kind: Kind1;
  x: X1;
  y: Y1;
  rotation_deg: RotationDeg;
  width_ft: WidthFt1;
  depth_ft: DepthFt;
  height_ft: HeightFt3;
}
/**
 * A unit-plan room type. Not a storey — instances live on floor-plan rooms.
 */
export interface TypeCatalogueEntry {
  type_ref: TypeRef1;
  name: Name2;
  label: Label;
  category: Category1;
  polygon: Polygon1;
  area_sqft: AreaSqft;
  aspect_ratio: AspectRatio;
  fixtures: Fixtures;
  instance_count: InstanceCount1;
  source: Source;
  [k: string]: unknown;
}
export interface CatalogueFixture {
  kind: Kind2;
  x: X2;
  y: Y2;
  asset_id: AssetId1;
  [k: string]: unknown;
}
export interface Environment {
  sun_azimuth: SunAzimuth;
  time: Time;
  season: Season;
  [k: string]: unknown;
}
/**
 * Where the building stands on the globe. Unsited projects leave lat/lon null.
 */
export interface Site {
  lat: Lat;
  lon: Lon;
  rotation_deg: RotationDeg1;
  ground_offset_ft: GroundOffsetFt;
  address: Address;
  [k: string]: unknown;
}
export interface ReviewItem {
  id: Id6;
  kind: Kind3;
  message: Message;
  document_id: DocumentId1;
  sheet_id: SheetId1;
  entity_ids: EntityIds;
  status: Status;
}
export interface DesktopProject {
  project_id: ProjectId;
  name: Name3;
  revision: Revision;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  brief: DesignBrief | null;
  building: Building;
  rules: Rules;
  checks: Checks;
  files: Files;
  sheets: Sheets;
  import_meta: ImportMeta;
  can_undo: CanUndo;
  can_redo: CanRedo;
  [k: string]: unknown;
}
export interface DesignBrief {
  name: Name4;
  building_use: BuildingUse;
  floors: Floors1;
  rooms: Rooms1;
  area: Area;
  style: Style;
  prompt: Prompt;
  [k: string]: unknown;
}
export interface ImportMeta {
  [k: string]: unknown;
}
export interface ModelCommand {
  kind: Kind4;
  target_id?: TargetId;
  params?: Params;
  [k: string]: unknown;
}
export interface Params {
  [k: string]: unknown;
}
